### ISSUE TITLE
code of normalization of point cloud seems different with paper

### ISSUE THREAD

**Issue by tornadomeet** [sergeyprokudin/bps#4]
hello, @sergeyprokudin 
in your paper, the normalization of one point clound is 
![image](https://user-images.githubusercontent.com/5860892/81643750-cb79a000-9458-11ea-859a-d6c636db6a08.png)

but in you code
https://github.com/sergeyprokudin/bps/blob/master/bps/bps.py#L48

it is 
```python
x_max = np.max(np.sqrt(np.sum(np.square(x), axis=1)))
```

so should we change the code like this?
```python
x_max = np.max(np.sqrt(np.sum(np.square(x_norm), axis=1)))
```
thanks!

**Comment by sergeyprokudin** [comment]
Hi @tornadomeet,

Indeed, this is a bug. Should be fixed now, thanks for noticing!
