### ISSUE TITLE
The link to download the pre-trianed model is 404

### ISSUE THREAD

**Issue by PeiLin-666** [sergeyprokudin/bps#6]
Thanks for your sharing! And I am looking for a method to register the human body, but the link you share is 404 now:( Maybe, it was too long ago.

**Running pre-trained model on your own 3D body scans: download the model checkpoint ([mirror](https://drive.google.com/open?id=19uJp7jeQRdx3rviE7VFD5GkglxvFbzfh)):**

**Comment by sergeyprokudin** [comment]
Hi @LinpeiSTU ,

here you go:

https://www.dropbox.com/s/u3d1uighrtcprh2/mesh_regressor.h5?dl=0

**Comment by PeiLin-666** [comment]
Thank you!
