### ISSUE TITLE
Metric for encoding efficiency

### ISSUE THREAD

**Issue by Ajay-2017** [sergeyprokudin/bps#7]
Hello,

Is there any metric to quickly assess the quality of the encoding
without going through the reconstruction workflow altogether .(using
the chamfer distance discussed in the paper)

That is just by encoding and from the placement of basis points in the
environment could you suggest any metric that indicates a good
starting point for the user on the encoding parameters.

I was thinking of coverage. (Number of unique points mapped by basis
points / total number of points in the environment (point cloud for
the cases considered in this paper)).
Any other metric do you think is useful which can give a rough idea on
the chosen parameter before going through the complete workflow?

Also, it would be helpful to know what you think about the coverage metric?

Thanks.

**Comment by sergeyprokudin** [comment]
Hi Ajay, thanks for your interest in the project!

The coverage metric you described makes sense. However, what is the problem with using Chamfer distance? Maybe this will help me to understand your usecase better, and propose something additionally.

Cheers,
Sergey

**Comment by Ajay-2017** [comment]
Thanks for the reply Sergey.
We are using basis points for representing occupancy map. Later we use this encoding and pass it to deep learning based motion planners, which helps find faster path for robots in conjunction with classical approaches.
In these use cases, we are not reconstructing the occupancy map as part of the workflow. 
Here to go for the entire workflow of training the network and finds that your encoding is poor from poor result of the motion planner is quite time consuming. 
Instead just after encoding the occupancy map using basis points and knowing whether our selected parameters work for the occupancy map using some metrics is useful.

**Comment by sergeyprokudin** [comment]
I see. Yes, the coverage makes sense then.
